### ISSUE TITLE
Un-explicit error message on empty changelog

### ISSUE THREAD

**Issue by larcin** [ForestAdmin/devops#5]
**Description**
When I try to release with an empty changelog, nothing is pushed to Slack and the error message isn't explicit. 

Steps to Reproduce
Trigger a release with an empty list of change

Expected behaviour
To see an error looking like "Your changelog is empty"

Actual behaviour
Release proceeds anyway and an error message telling the slack token is invalid is shown.

**Comment by arnaudbesnier** [comment]
Feature removed since "conventional commits" + "semantic releases" implementation
